package UI;

import javax.swing.DefaultComboBoxModel;
import managers.SystemManager;
import objects.User;
import UI.LoginUI;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import managers.OrderedItemManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Karinak
 */
public class WaiterUI extends javax.swing.JFrame {

    private SystemManager systemManager;
    private int waiterID = 0; 
     //this needs to be set to logins 

    /**
     * Creates new form HomeScreenAdminUI
     */
    public WaiterUI(int input) throws SQLException, FileNotFoundException {
        initComponents();
    waiterID = input; 
      
        systemManager = new SystemManager();
        this.populateTypeCombobox();
        this.populateOrdersTableForWaiter();
        this.populateMenuTableForOrder();
        this.setOrderTabelSelectionModel();
        this.populateStudentTable();
        this.setActionCommands();

    }
    
    

    public void setActionCommands() {
        cardradiobutton.setActionCommand("card");
        cashRadioButton.setActionCommand("cash");
        zapperRadioButton.setActionCommand("zapper");

        collectedRadioButton.setActionCommand("1");
        notCollectedRadioButton.setActionCommand("0");

    }

    public void populateTypeCombobox() {
        DefaultComboBoxModel<String> comboModelTypes = new DefaultComboBoxModel<String>();
        String[] types = systemManager.tm.typesForCombobox();
        for (int i = 0; i < systemManager.tm.getSize(); i++) {
            comboModelTypes.addElement(types[i]);
        }
        menuTypeComboBox.setModel(comboModelTypes);
    }

    private void populateStudentTable() throws SQLException {
        int grade = ((Integer) (studentGradeSpinner.getValue())).intValue();
        systemManager.initialiseStudentManagerForGrade(grade);
        studentTable.setModel(systemManager.sm);
    }

    private void populateOrdersTableForWaiter() throws SQLException {
        systemManager.initialiseSpecificWaiterOrders(waiterID);
        ordersTable.setModel(systemManager.om);
    }

    private void popualteAllOrders() throws SQLException {
        systemManager.initialiseAllOrders();
        ordersTable.setModel(systemManager.om);
    }

    public void populateMenuTableForOrder() throws SQLException {
        String type = (String) menuTypeComboBox.getSelectedItem();
        systemManager.initialiseMenuManagerToPlaceOrder(type);
        menuItemsTable.setModel(systemManager.mm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        paymentMethodButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        collectedButtonGroup = new javax.swing.ButtonGroup();
        ordersButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        FAQsPane = new javax.swing.JTabbedPane();
        viewOrdersPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        currentOrderTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        myOrdersButton = new javax.swing.JRadioButton();
        allOrdersRadioButton = new javax.swing.JRadioButton();
        faqsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewOrdershelpButton = new javax.swing.JButton();
        placeOrderHelpButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        helpmessageTextArea = new javax.swing.JTextArea();
        placeOrderPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuItemsTable = new javax.swing.JTable();
        menuTypeComboBox = new javax.swing.JComboBox<>();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderedItemsTable = new javax.swing.JTable();
        addToOrderbutton = new javax.swing.JButton();
        removeFromOrderButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cardradiobutton = new javax.swing.JRadioButton();
        cashRadioButton = new javax.swing.JRadioButton();
        zapperRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        addOrderRadioButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        totalPriceTextAreas = new javax.swing.JTextArea();
        studentGradeSpinner = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        notCollectedRadioButton = new javax.swing.JRadioButton();
        collectedRadioButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FAQsPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Order", "Total", "Collected "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(ordersTable);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel7.setText("ORDERS");

        currentOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Price", "Quantity"
            }
        ));
        jScrollPane7.setViewportView(currentOrderTable);

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel9.setText("ORDERRED ITEMS");

        ordersButtonGroup.add(myOrdersButton);
        myOrdersButton.setSelected(true);
        myOrdersButton.setText("MY ORDERS ONLY");
        myOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOrdersButtonActionPerformed(evt);
            }
        });

        ordersButtonGroup.add(allOrdersRadioButton);
        allOrdersRadioButton.setText("ALL ORDERS ");
        allOrdersRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allOrdersRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewOrdersPanelLayout = new javax.swing.GroupLayout(viewOrdersPanel);
        viewOrdersPanel.setLayout(viewOrdersPanelLayout);
        viewOrdersPanelLayout.setHorizontalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myOrdersButton)
                            .addComponent(allOrdersRadioButton)))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel9)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        viewOrdersPanelLayout.setVerticalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(myOrdersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allOrdersRadioButton)))
                .addGap(97, 97, 97)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        FAQsPane.addTab("View orders", viewOrdersPanel);

        viewOrdershelpButton.setText("View Orders");
        viewOrdershelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdershelpButtonActionPerformed(evt);
            }
        });

        placeOrderHelpButton.setText("Place Order");
        placeOrderHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderHelpButtonActionPerformed(evt);
            }
        });

        helpmessageTextArea.setColumns(20);
        helpmessageTextArea.setLineWrap(true);
        helpmessageTextArea.setRows(5);
        jScrollPane8.setViewportView(helpmessageTextArea);

        javax.swing.GroupLayout faqsPanelLayout = new javax.swing.GroupLayout(faqsPanel);
        faqsPanel.setLayout(faqsPanelLayout);
        faqsPanelLayout.setHorizontalGroup(
            faqsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faqsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(faqsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(placeOrderHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOrdershelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        faqsPanelLayout.setVerticalGroup(
            faqsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faqsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(faqsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(faqsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(viewOrdershelpButton)
                        .addGap(18, 18, 18)
                        .addComponent(placeOrderHelpButton)))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        FAQsPane.addTab("FAQs", faqsPanel);

        menuItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuItemsTable);

        menuTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MENU ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CURRENT ORDER");

        orderedItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Item Type", "Quantity ", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderedItemsTable);

        addToOrderbutton.setText("ADD TO ORDER");
        addToOrderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToOrderbuttonActionPerformed(evt);
            }
        });

        removeFromOrderButton.setText("REMOVE FROM ORDER");
        removeFromOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromOrderButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Payment Method: ");

        paymentMethodButtonGroup.add(cardradiobutton);
        cardradiobutton.setSelected(true);
        cardradiobutton.setText("Card");
        cardradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardradiobuttonActionPerformed(evt);
            }
        });

        paymentMethodButtonGroup.add(cashRadioButton);
        cashRadioButton.setText("Cash");

        paymentMethodButtonGroup.add(zapperRadioButton);
        zapperRadioButton.setText("Zapper");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("STUDENT");

        addOrderRadioButton.setText("ADD ORDER");
        addOrderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderRadioButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("TOTAL PRICE: ");

        totalPriceTextAreas.setColumns(20);
        totalPriceTextAreas.setRows(5);
        jScrollPane3.setViewportView(totalPriceTextAreas);

        studentGradeSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        studentGradeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                studentGradeSpinnerStateChanged(evt);
            }
        });

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(studentTable);

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Is order collected: ");

        collectedButtonGroup.add(notCollectedRadioButton);
        notCollectedRadioButton.setSelected(true);
        notCollectedRadioButton.setText("Not collected");

        collectedButtonGroup.add(collectedRadioButton);
        collectedRadioButton.setText("Collected");

        javax.swing.GroupLayout placeOrderPanelLayout = new javax.swing.GroupLayout(placeOrderPanel);
        placeOrderPanel.setLayout(placeOrderPanelLayout);
        placeOrderPanelLayout.setHorizontalGroup(
            placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(menuTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(190, 190, 190))
            .addGroup(placeOrderPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(placeOrderPanelLayout.createSequentialGroup()
                            .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(placeOrderPanelLayout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(studentGradeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(103, 103, 103)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addToOrderbutton)
                        .addGroup(placeOrderPanelLayout.createSequentialGroup()
                            .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(placeOrderPanelLayout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(placeOrderPanelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(notCollectedRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(collectedRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addGap(146, 146, 146))
                        .addGroup(placeOrderPanelLayout.createSequentialGroup()
                            .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addOrderRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(placeOrderPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cardradiobutton)
                                    .addGap(36, 36, 36)
                                    .addComponent(cashRadioButton)
                                    .addGap(34, 34, 34)
                                    .addComponent(zapperRadioButton)
                                    .addGap(288, 288, 288)
                                    .addComponent(removeFromOrderButton)))
                            .addGap(0, 17, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        placeOrderPanelLayout.setVerticalGroup(
            placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placeOrderPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(placeOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addToOrderbutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardradiobutton)
                            .addComponent(cashRadioButton)
                            .addComponent(zapperRadioButton)))
                    .addGroup(placeOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeFromOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(notCollectedRadioButton)
                    .addComponent(collectedRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(placeOrderPanelLayout.createSequentialGroup()
                        .addGroup(placeOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(studentGradeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(placeOrderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(addOrderRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
        );

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        studentGradeSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        FAQsPane.addTab("Place order", placeOrderPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FAQsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FAQsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardradiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardradiobuttonActionPerformed

    private void menuTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTypeComboBoxActionPerformed
        try {
            // TODO add your handling code here:
            this.populateMenuTableForOrder();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuTypeComboBoxActionPerformed

    private void addToOrderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToOrderbuttonActionPerformed
        // TODO add your handling code here:
        int itemId = (int) menuItemsTable.getValueAt(menuItemsTable.getSelectedRow(), 0);
        String itemname = (String) menuItemsTable.getValueAt(menuItemsTable.getSelectedRow(), 1);
        String itemtype = (String) menuItemsTable.getValueAt(menuItemsTable.getSelectedRow(), 2);
        double price = (double) menuItemsTable.getValueAt(menuItemsTable.getSelectedRow(), 3);
        int quntity = (int) quantitySpinner.getValue();

        systemManager.oim.addOrderedItem(itemId, itemname, itemtype, price, quntity);
      
        this.populateOrderedItemTable();
        this.updateTotalPrice();

    }//GEN-LAST:event_addToOrderbuttonActionPerformed

    private void updateTotalPrice() {
        totalPriceTextAreas.setText(Double.toString(systemManager.oim.getTotalPriceOfOrder()));
    }
    private void removeFromOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromOrderButtonActionPerformed
        // TODO add your handling code here:
        int menuID = 0; 
        menuID = (int) orderedItemsTable.getValueAt(orderedItemsTable.getSelectedRow(), 0);
        if(menuID == 0){ 
            JOptionPane.showMessageDialog(null, "Select an ordereditem to remove from the order");
        }
        else { 
        systemManager.oim.deleteOrderedItem(menuID);
        this.populateOrderedItemTable();
        this.updateTotalPrice();
        } 

    }//GEN-LAST:event_removeFromOrderButtonActionPerformed

    private void studentGradeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_studentGradeSpinnerStateChanged
        try {
            // TODO add your handling code here:
            this.populateStudentTable();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentGradeSpinnerStateChanged

    private void addOrderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderRadioButtonActionPerformed
        // TODO add your handling code here:
        int studentID = 0; 
        studentID = ((Integer) studentTable.getValueAt(studentTable.getSelectedRow(), 0)).intValue();
        String paymentMethod = (String) paymentMethodButtonGroup.getSelection().getActionCommand();
        int collectedInt = Integer.parseInt(collectedButtonGroup.getSelection().getActionCommand());
//       boolean collected = false; 
//        if(collectedInt == 1)
//            collected = true; 


if(studentID == 0){ 
    JOptionPane.showMessageDialog(null, "Select a student");
}
else{ 
        int orderId =0;
        try {
            orderId = systemManager.om.getNextOrderID();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(orderId);
        try {
            systemManager.oim.addToDatabase(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            systemManager.om.addOrder(studentID, paymentMethod, waiterID, collectedInt);
            this.populateOrdersTableForWaiter();
            this.populateOrdersTableForWaiter();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Order successfully added");
        this.setOrderedItemTableToDefault();

} 

    }//GEN-LAST:event_addOrderRadioButtonActionPerformed

    private void myOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOrdersButtonActionPerformed
        try {
            // TODO add your handling code here:
            this.populateOrdersTableForWaiter();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_myOrdersButtonActionPerformed

    private void allOrdersRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allOrdersRadioButtonActionPerformed
        try {
            // TODO add your handling code here:
            this.popualteAllOrders();
        } catch (SQLException ex) {
            Logger.getLogger(WaiterUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_allOrdersRadioButtonActionPerformed

    private void viewOrdershelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdershelpButtonActionPerformed
        // TODO add your handling code here:
        helpmessageTextArea.setText(systemManager.hsm.getMessage(6));
    }//GEN-LAST:event_viewOrdershelpButtonActionPerformed

    private void placeOrderHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderHelpButtonActionPerformed
        // TODO add your handling code here:
           helpmessageTextArea.setText(systemManager.hsm.getMessage(7));
    }//GEN-LAST:event_placeOrderHelpButtonActionPerformed

    private void populateOrderedItemTable() {
       this.setOrderedItemTableToDefault();
        orderedItemsTable.setModel(systemManager.oim);
    }
    
    private void setOrderedItemTableToDefault(){ 
         DefaultTableModel dtm = new DefaultTableModel(); 
        orderedItemsTable.setModel(dtm);
    }

  

    private void setOrderTabelSelectionModel() {
        ordersTable.setRowSelectionAllowed(true);
        ListSelectionModel cellSelectionModel = ordersTable.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int id = ((Integer) ordersTable.getValueAt(ordersTable.getSelectedRow(), 0)).intValue();
                try {
                    systemManager.initialiseOrderManager(id);
                    currentOrderTable.setModel(systemManager.orm);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane FAQsPane;
    private javax.swing.JButton addOrderRadioButton;
    private javax.swing.JButton addToOrderbutton;
    private javax.swing.JRadioButton allOrdersRadioButton;
    private javax.swing.JRadioButton cardradiobutton;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.ButtonGroup collectedButtonGroup;
    private javax.swing.JRadioButton collectedRadioButton;
    private javax.swing.JTable currentOrderTable;
    private javax.swing.JPanel faqsPanel;
    private javax.swing.JTextArea helpmessageTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable menuItemsTable;
    private javax.swing.JComboBox<String> menuTypeComboBox;
    private javax.swing.JRadioButton myOrdersButton;
    private javax.swing.JRadioButton notCollectedRadioButton;
    private javax.swing.JTable orderedItemsTable;
    private javax.swing.ButtonGroup ordersButtonGroup;
    private javax.swing.JTable ordersTable;
    private javax.swing.ButtonGroup paymentMethodButtonGroup;
    private javax.swing.JButton placeOrderHelpButton;
    private javax.swing.JPanel placeOrderPanel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JButton removeFromOrderButton;
    private javax.swing.JSpinner studentGradeSpinner;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextArea totalPriceTextAreas;
    private javax.swing.JPanel viewOrdersPanel;
    private javax.swing.JButton viewOrdershelpButton;
    private javax.swing.JRadioButton zapperRadioButton;
    // End of variables declaration//GEN-END:variables
}
